### ISSUE TITLE
Unexpected Error after selecting SonarQube Runner in build step configuration

### ISSUE THREAD

**Issue by randrey** [JetBrains/TeamCity.SonarQubePlugin#1]
This is the error we get:

```
Unexpected Error

This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
If you maintain this TeamCity installation please report this error to JetBrains.

Error message: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.ServletException: org.apache.jasper.JasperException: /plugins/sonar-plugin/editSQRRunParams.jsp (line: 87, column: 0) No tag "javaSettings" defined in tag library imported with prefix "props"
TeamCity: 8.0.5 (build 27692)
Operating system: Windows 2003 (5.2, x86)
Java: 1.7.0_21-b11 (Oracle Corporation)
Servlet container: Apache Tomcat/7.0.37
```

![sonarqubeerror](https://cloud.githubusercontent.com/assets/798485/3860325/d7285eac-1f22-11e4-99b5-9c93bacf6681.png)

The plugin was installed as described [here](http://confluence.jetbrains.com/display/TW/SonarQube+Integration). 

Is there some additional configuration we need to do?

**Comment by vigneshsonar** [comment]
Do have any other method to implement without upgrading teamcity

**Comment by Linfar** [comment]
@vigneshsonar For TC 8 you can use [Meta Runner] (https://github.com/jetbrains/meta-runner-power-pack) or just maven sonar:sonar goal

**Comment by Nipun07** [comment]
@Linfar what should be put in filed "Sonar Runner executable" while configuring sonar runner in build step?
