### ISSUE TITLE
Plugin not picking up sonar-project.properties file

### ISSUE THREAD

**Issue by bravous** [JetBrains/TeamCity.SonarQubePlugin#17]
In the project there is a `sonar-project.properties` at the project root level. When i run a local sonar-runner this property file is picked up. However when I run the runner from TeamCity the file is not ignored, the log reads:

```
[13:10:25][Step 1/1] SonarQube Runner 2.4
[13:10:25][Step 1/1] Java 1.8.0_66-internal Oracle Corporation (64-bit)
[13:10:25][Step 1/1] Linux 3.16.0-0.bpo.4-amd64 amd64
[13:10:25][Step 1/1] INFO: Runner configuration file: NONE
[13:10:25][Step 1/1] INFO: Project configuration file: NONE
```

Expected is that the property file is picked up and the properties are used, unless they are overwritten.

**Comment by bravous** [comment]
When i change the 'sonar runner' build step config and add the additional parameter:

```
-Dproject.home=%teamcity.build.checkoutDir%
```

The property file is picked up correctly. Think this should be standard behavior and added by the runner itself.

**Comment by Linfar** [comment]
I've added a field for editing working directory. However it was always set by default to checkout directory so I'll check whether SonarQube Runner respects the working directory as project home path
