### ISSUE TITLE
Database-Less Scanning

### ISSUE THREAD

**Issue by dploeger** [JetBrains/TeamCity.SonarQubePlugin#18]
Is it possible to use SonarQube >=5.3 with the current version of the plugin, which includes [database-less scanning](http://www.sonarqube.org/sonarqube-5-2-in-screenshots/) or does the included runner need an update?

**Comment by Linfar** [comment]
Everything seems to be working fine. I've tested current TeamCity plugin (with SonarQube Runner 2.4) and SonarQube server v5.3.
