### ISSUE TITLE
Configurated sonar-scanner and sonar-server by separated

### ISSUE THREAD

**Issue by renzors** [JetBrains/TeamCity.SonarQubePlugin#21]
Hi, I wish have the sonar-scanner and sonar-server in 2 different servers, what can I configure the plugin to support it? Thanks.

**Comment by Linfar** [comment]
I'm really sorry I've missed this message. Is it still actual?

**Comment by renzors** [comment]
I've missed this message too. In fact, I was wrong at that moment, now understand that the sonar-scanner run on agents of TeamCity. I think that you can close this issue. Thanks a lot.
