### ISSUE TITLE
Run SonarQube Analysis fails on TeamCity 10

### ISSUE THREAD

**Issue by bsiegel** [JetBrains/TeamCity.SonarQubePlugin#23]
Just upgraded to TeamCity 10 and builds with the Run SonarQube Analysis step are failing. In the log I see:

```
Parameter "secure:teamcity.password.33815514-c1a4-489b-9c52-b550fcc4e00f.sonarPassword" is undefined.
Parameter "secure:teamcity.password.33815514-c1a4-489b-9c52-b550fcc4e00f.sonar.jdbc.password" is undefined.

<snip>

ERROR: Unable to execute Sonar
ERROR: Caused by: Not authorized. Please check the properties sonar.login and sonar.password.
```

I tried removing my Sonar server and re-adding it, but this didn't fix the issue.

**Comment by dotnetneile** [comment]
I've had this also. I didn't manage to find a fix but I did mange to get further when I set these as additional properties. Not ideal but as a temp workaround may help. Until the issue is fixed of course.

-Dsonar.login=xxxxx
-Dsonar.password=xxxxx

I have also upgraded to Sonar 5.6 which is causing other issues.

**Comment by mvossi** [comment]
For the workaround mentioned before, enter these two properties in:
Build Step > SonarQube Runner > Additional Parameters

**Comment by pavelsher** [comment]
Please try installing this version of the plugin:
https://teamcity.jetbrains.com/viewLog.html?buildId=829128&tab=artifacts&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build100x

**Comment by bsiegel** [comment]
@pavelsher That build appears to fix the issue, thanks!

**Comment by dotnetneile** [comment]
@pavelsher works for me as well.

**Comment by ddatsh** [comment]
@pavelsher ,I reinstall the plugin,see version=100 in teamcity 10,and still 
ERROR: Caused by: Not authorized. Please check the properties sonar.login and sonar.password.

**Comment by gaurarpit12** [comment]
I am trying to run sonarqube on a .net project in teamcity.
But my step is failing and I am getting the following as the build log:
![image](https://cloud.githubusercontent.com/assets/20061410/18274684/4cce96e0-7461-11e6-8f2d-c4db6cfdb876.png)

**Comment by sshulisr** [comment]
Similar issue after update to  10.0.1 (build 42078)
sonar-plugin version is 31

![capture11](https://cloud.githubusercontent.com/assets/22032542/18281273/f1e57cf4-7464-11e6-913c-acaec373503e.PNG)

**Comment by gaurarpit12** [comment]
@sshulisr 
Firstly stop the sonar service, then try running sonarquebe on different port.

**Comment by Linfar** [comment]
@sshulisr Is your SonarQube Server running on the same machine where TeamCity Agent is runnnig?

**Comment by Linfar** [comment]
I'm closing this ticket as initial problem was solved. Please open a new one if needed.
