### ISSUE TITLE
Update plugin download link in readme.txt for TC10

### ISSUE THREAD

**Issue by mvossi** [JetBrains/TeamCity.SonarQubePlugin#26]
The readme.txt (at the sonar-plugin GitHub main page) shows a link to TC9.x sonar-plugin. There should be an additional link to the latest sonar-plugin for TC10 users, because the 9.x plugin is not working on 10.x.

I downloaded the latest from https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build100x

**Comment by Linfar** [comment]
Thanks for noting
