### ISSUE TITLE
Change special characters for project key

### ISSUE THREAD

**Issue by renzors** [JetBrains/TeamCity.SonarQubePlugin#27]
Before that run the analyse process, I need to change some special characters for project key. How can I do that?

**Comment by Linfar** [comment]
@renzors Can you be more specific?

**Comment by renzors** [comment]
Sure. I am using four tools: Stash, TeamCity, Sonar for Stash and SonarQube. 

When I make a change on stash, that run a build process in teamcity and in my process I set the project key, in my case is the same name of branch on stash. It must be the branch name because in a second time I use sonar for stash to analyze the pull request issues, but this tool search a project key in sonarqube named as the branch.

All is fine, except when the branch name have a special characters as # for example. So, currently I get the branch name through of a parameter, but I'd like will can replace the characters as part of configuration. I think that it is a reason because in sonar for stash exist a field for replace special characters, i suppose because it is recurrent.

**Comment by Linfar** [comment]
@renzors Ok, now I got it. There is no such functionality in TeamCity. As a workaround you can modify this parameter in a separate build step before Sonar analysis (refer to [service message documentation](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-changingBuildParameterAddingorChangingaBuildParameterfromaBuildStepAddingorChangingaBuildParameter)).
On the other hand this looks like it should be done inside TeamCity SonarQube plugin. I'll try to fix it tomorrow.

**Comment by renzors** [comment]
Nice @Linfar I will be expectant :-)

**Comment by Linfar** [comment]
@renzors You can update the plugin from [CI](https://teamcity.jetbrains.com/project.html?projectId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin&branch_TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin=%3Cdefault%3E)

**Comment by renzors** [comment]
@Linfar Thanks a lot  :-)
