### ISSUE TITLE
Sonar Build error after Sonar version upgrade

### ISSUE THREAD

**Issue by dpadhya1990** [JetBrains/TeamCity.SonarQubePlugin#32]
Hello team 
We have recently upgrade our sonar Dev server Following are the details of the same
Sonar server : 4.5.2 to 5.6.3, 
C# plugin : 3.3 to 5.3.2
Sonar runner (sonar scanner) : 2.4 to 2.8 
post upgrade our XAML build is getting partially succeeded error warning is 
15:05:30.046 WARN: ***********************************************************************************
15:05:30.046 WARN: * Use MSBuild 14 to get the best analysis results *
15:05:30.046 WARN: * The use of MSBuild 12 or the sonar-scanner to analyze C# projects is DEPRECATED *
15:05:30.046 WARN: ***********************************************************************************
But our msbuild version in sonar server is 14 only, 

Regards
Dushyant Padhya

**Comment by Linfar** [comment]
@dpadhya1990, this is just a warning message recommending to use [MSBuild integration](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild). Currently this feature is not supported in TeamCity. 
Do you get problems analyzing with TeamCity plugin after update?

**Comment by dpadhya1990** [comment]
Thanks Linfar for the reply
even though its warning our build is not successful and we cannot generate sonar dashboard due to that, our MSBuild Version is 14 still showing warning to use MSBuild 14 version
and we are not using TeamCity plugin we just upgraded sonar server, sonar scanner and C# plugin

**Comment by Linfar** [comment]
@dpadhya1990 Could you send me a build log? Better to andrey.titov@jetbrains.com

**Comment by dpadhya1990** [comment]
Hello andrey 
I have sent you build logs on your mentioned Email ID can you please confirm if you received the same 

Regards
Dushyant Padhya

**Comment by Linfar** [comment]
Yes, I've received it. Do you run Sonar through TeamCity?

**Comment by dpadhya1990** [comment]
No we dont use team city, we use sonar runner ( now sonar scanner after upgrade) and sonarqube in TFS

**Comment by Linfar** [comment]
Then you better ask guys from Sonar team - here I can only help with
TeamCity related problems. Try asking on
https://jira.sonarsource.com/browse/SONARMSBRU/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
- it's MSBuild integration issuetracker.
