### ISSUE TITLE
Update packaged SonarQube Scanner to 2.8

### ISSUE THREAD

**Issue by alawrenc** [JetBrains/TeamCity.SonarQubePlugin#33]
The packaged version is at version 2.4. Moving to [2.8](https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.8.zip) to pick up new features would be ideal.

**Comment by axel3rd** [comment]
+1 vote [v3.+](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) :smile:

**Comment by Linfar** [comment]
I almost finished implementing [Tools support](https://confluence.jetbrains.com/display/TCD10/Installing+Agent+Tools) for Sonar plugin so that it would be possible to update the Scanner manually. Currently I've added version 3.0.3.778 (latest) as second bundled version.

**Comment by axel3rd** [comment]
> Currently I've added version 3.0.3.778 (latest) as second bundled version.

I promote the last as first (default).

**Comment by Linfar** [comment]
The feature is finished, you can check the [new plugin version](https://teamcity.jetbrains.com/viewLog.html?buildId=1243110&tab=artifacts&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build20171x). The new functionality works with TeamCity 2017.1 and higher.
