### ISSUE TITLE
unrecognised sonar.projectKey and sonar.sources

### ISSUE THREAD

**Issue by grove825** [JetBrains/TeamCity.SonarQubePlugin#34]
Get a Error: ERROR: Caused by: You must define the following mandatory properties for 'Unknown': *******.projectKey, *******.sources

but I did provided it:
C:\TeamCity\buildAgent\plugins\*******-plugin-agent\*******-qube-runner\bin\*******-runner.bat -Dproject.home=. -D*******.host.url=http://localhost/ -D*******.jdbc.url=jdbc:mysql://localhost:3306/*******?useUnicode=true&useConfigs=maxPerformance -D*******.jdbc.username=******* -D*******.jdbc.password=******* -D*******.projectKey=Fab -D*******.projectName=UnitTests -D*******.projectVersion=135 -D*******.sources=Fab -D*******.password=******* -D*******.login=******* -D*******.python.coverage.reportPath=cov.xml

TeamCity 10.0.3
SonarQube 6.1

**Comment by Linfar** [comment]
@grove825 I've reproduced your problem. As a workaround you can remove '&useConfigs=maxPerformance' from your jdbc url or add escaping for '&' symbol.

**Comment by Linfar** [comment]
@grove825 Fix is ready, you can download updated plugin from [here](https://teamcity.jetbrains.com/viewLog.html?buildId=940931&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build100x&tab=artifacts)
