### ISSUE TITLE
Special characters are not handled correctly in generated CLI command

### ISSUE THREAD

**Issue by boonen** [JetBrains/TeamCity.SonarQubePlugin#36]
Our SonarQube user has a password with special characters, but unfortunately the plugin does not put the SQ runner command line arguments in quotes. Therefore our builds fail with the following exceptions:
- On Windows (a shell exception):
The filename, directory name, or volume label syntax is incorrect.
- On Linux (a Java exception):
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Not authorized. Please check the properties sonar.login and sonar.password.
ERROR: Caused by: Fail to download [http://localhost/batch/global]. Response code: 401

Command to test:
```C:\BuildAgent\plugins\sonar-plugin-agent\sonar-qube-runner\bin\sonar-runner.bat -Dproject.home=. -Dsonar.host.url=http://localhost -Dsonar.projectKey=mykey -Dsonar.projectName=myproject -Dsonar.projectVersion=1.0.0 -Dsonar.sources=mysources -Dsonar.tests=MyTest -Dsonar.password=passwrord;withspeci@l>characters! -Dsonar.login=myuser```

A simple solution would be to put all SQ parameter values in double quotes (I can apply a fix via a PR).

**Comment by Linfar** [comment]
@boonen What plugin version and what java version on agent do you use?

**Comment by boonen** [comment]
We use the plugin version from https://teamcity.jetbrains.com/viewLog.html?buildId=879040&tab=artifacts&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build and Oracle Java 1.8.0 (update 66).

However, I now see that there is a separate plugin build for TC 10, so I don't know if that will solve our issue. I'll try right now and keep you informed.

**Comment by boonen** [comment]
@Linfar It seems that the TC10 version fixed the problem. Now the listed plugin version is 116. Sorry for bothering you.
