### ISSUE TITLE
SonarScanner for MSBuild: finish analysis fails due to inability to specify a working directory

### ISSUE THREAD

**Issue by KellyR-STCU** [JetBrains/TeamCity.SonarQubePlugin#51]
I was testing out the updated version of this plugin with MSBuild today and there is a problem when specifying a working directory in the initial scan step:

SonarScanner for MSBuild: begin analysis (5s)
in directory: C:\buildAgent\work\ea436c88452306fe\src

SonarScanner for MSBuild: finish analysis
Starting: C:\buildAgent\tools\sonar-scanner-msbuild.4.0.2.892\MSBuild.SonarQube.Runner.exe end
 in directory: C:\buildAgent\work\ea436c88452306fe

The result:

Temporary analysis directory (usually .sonarqube) doesn't exist. The "begin" step was probably not executed.
Post-processing failed. Exit code: 1

We need to be able to specify the working directory in the end step as well.

**Comment by KellyR-STCU** [comment]
@Linfar Any idea if you might be able to take a look at this?

**Comment by Linfar** [comment]
I'll check it and fix when possible. Meanwhile you can try using default working directory and use "sonar.projectBaseDir" additional parameter.

**Comment by Linfar** [comment]
The fix was simple so I've integrated it to both version ([10.0.x](https://teamcity.jetbrains.com/viewLog.html?buildId=1521404&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build100x&tab=artifacts) and [2017.1.x](https://teamcity.jetbrains.com/viewLog.html?buildId=1521403&buildTypeId=TeamCityPluginsByJetBrains_TeamCitySonarQubePlugin_Build20171x&tab=artifacts))

**Comment by KellyR-STCU** [comment]
Thank you!!

**Comment by KellyR-STCU** [comment]
@Linfar After updating, I am not seeing the Working Directory exposed to be configured in the SonarScanner for MSBuild: finish analysis step in TeamCity.

Is this supposed to just work automatically?

**Comment by Linfar** [comment]
Yes, working directory for finish step will be used from begin step

чт, 12 июл. 2018 г., 21:36 KellyR-STCU <notifications@github.com>:
