### ISSUE TITLE
Unable to build from source missing jar in repository folder

### ISSUE THREAD

**Issue by bdbogjoe** [JetBrains/TeamCity.SonarQubePlugin#55]
here my error : 

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (org.jetbrains.teamcity:common-tools) on project repository: The specified file '/home/......./TeamCity.SonarQubePlugin/repository/lib/common-tools.jar' not exists -> [Help 1]
`

Seems one local jar is missing in repository folder

**Comment by axel3rd** [comment]
Required JARs are `common-tools.jar` & `server-tools.jar`, but not findable in https://download.jetbrains.com/teamcity-repository or in TeamCity achive.
No idea where found them, as workaround 😢.

**Comment by Linfar** [comment]
Which branch and which modification do you try to build?

**Comment by Linfar** [comment]
Ah, ok, I've understood the problem. You should place these 2 jars to the `repository/lib/`. Jars could be found in TC server distribution in `webapps/ROOT/WEB-INF/lib/`.

**Comment by Linfar** [comment]
I see in in 2017.1 (`servers/2017.1/buildAgent/lib/common-tools.jar`) but it seems 2019.1 don't contain it. Probably this jar isn't needed now but I have to check it. 
BTW you can use `mvn tc-sdk:start` and a TC distribution will be downloaded and unpacked to `servers` folder. Then you can just copy needed jar from downloaded location.
