### ISSUE TITLE
'MSBuild.SonarQube.Runner.exe' is deprecated

### ISSUE THREAD

**Issue by kemsky** [JetBrains/TeamCity.SonarQubePlugin#56]
> [02:38:34]	[Step 5/18] WARNING: ------------------------------------------------------------------------
> [02:38:34]	[Step 5/18] This executable is deprecated and may be removed in next major version of the SonarScanner for MSBuild. Please use 'SonarScanner.MSBuild.exe' instead.
> [02:38:34]	[Step 5/18] ------------------------------------------------------------------------

**Comment by MuhKuh7** [comment]
Any news?

**Comment by dro123** [comment]
Any news?
It was removed in version 5.
So the max version that can be used right now with the plugin is the latest 4.x.

**Comment by olsh** [comment]
We should probably vote for the issue here https://youtrack.jetbrains.com/issue/TW-69007
It seems like JetBrains team doesn't pay much attention to GitHub issues

**Comment by bade7n** [comment]
New version is available for download here https://plugins.jetbrains.com/plugin/9094-sonar-runner/versions?preview=true

**Comment by tallior** [comment]
This issue is not resolved for me - can't install the latest runner version...

**Comment by frodgim** [comment]
Please open because it is not working at all.
