### ISSUE TITLE
Not working with SonarQube Server 7.9

### ISSUE THREAD

**Issue by kozekocha** [JetBrains/TeamCity.SonarQubePlugin#64]
The plugin doesn't work with SonarQube 7.9. The internally used Sonar Runner 2.4 uses an API which is not available.
In particular this is 'batch_bootstrap/index' which is not available and should be replaced with 'batch/index'
[Web API](https://sonarcloud.io/web_api/batch?deprecated=true&internal=true)

I'm aware that the Sonar Runner is not under your control but once this was updated the plugin should be updated as well. 

I've already raised a ticket for the [Sonar Runner](https://community.sonarsource.com/t/sonar-runner-uses-wrong-api-teamcity-plugin/13096)

Regards,
Andre

**Comment by Linfar** [comment]
Hello

What plugin version do you use?

**Comment by kozekocha** [comment]
2017.1-22

**Comment by Linfar** [comment]
Then you can choose between Sonar Runner 2.4 and 3.0.3 - both versions are bundled. Please try the 3.0.3 version - you can make it default in Administration -> Tools page or select a version in the Sonar Runner step.

**Comment by kozekocha** [comment]
Oh, good to know. I'll try that. And thank you for the very fast response :)

**Comment by kozekocha** [comment]
It's working as you said. Issue solved.

**Comment by kozekocha** [comment]
working as expected

**Comment by Linfar** [comment]
Thanks for update
