### ISSUE TITLE
Make user tokens secrets

### ISSUE THREAD

**Issue by Tarig0** [JetBrains/TeamCity.SonarQubePlugin#74]
Currently to get the access token feature to function we have to send it as the user parameter to the SQ server. This shows in the build log exposing to token.

Please add a new parameter for accesstoken so it can be treated as a secret or set the current use parameter to be a secret as well.

**Comment by Linfar** [comment]
I've implemented this feature, now it's possible to set token authentication for the connection. It's integrated both to 2017.1 and 2020.1 branches (please note that Sonar Runner plugin 2017.1 is incompatible with TeamCity 2020.1).
