### ISSUE TITLE
MSBuild scanner fails due to "GC overhead limit"

### ISSUE THREAD

**Issue by tallior** [JetBrains/TeamCity.SonarQubePlugin#88]
I am using the SonarQube plugin (bundled with TC - [Step 4/4] INFO: SonarQube Scanner 3.2.0.1227)

I have a very large report that is generated, which makes the final step (the "end" phase of the MSBuild scanner) fail:

[08:27:41]	[Step 4/4] ERROR: Failed parsing JSON source: JsonReader at line 5366768 column 35 path $.runs[0].results[233727].locations[0].resultFile.region.startLine to Json
[08:27:41]	[Step 4/4] ERROR: Caused by: GC overhead limit exceeded

Is there any way to overcome this? maybe by specifying memory options for the scanner ? i could not find the option to add this to the "SonarQube finish analysis" step.

This post mentions that it's possible to overcome by specifying some command line memory options: https://stackoverflow.com/questions/24362982/gc-overhead-limit-exceeded-while-running-sonar-runner

**Comment by Linfar** [comment]
Hello

There is a "JVM command line parameters" field in the SonarQube Runner (under advanced options). There you can specify Xmx for the spawned process.
